name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: Debug Application
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON_RAW }}
        packageName: in.aditya.adityacicdapp
        releaseFiles: app/build/outputs/apk/debug/app-debug.apk
        track: internalsharing
        inAppUpdatePriority: 0
        userFraction: 0.1
        #whatsNewDirectory: aditya-ci-cd-app/whatsNewDirectory/whatsnew-en-US

        #mappingFile: app/build/outputs/mapping/release/mapping.txt

