name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDevDebug
      
    - name: Create service_account.json
      run: echo '${{ secrets.SERVICE_ACCOUNT_JSON_RAW }}' > service-account-json-raw
      
    - name: Promote Google Play open testing to production
      uses: boswelja/promote-play-beta-action@v1.0.0
      with: 
       service-account-json-raw: service-account-json-raw
       packageName: in.aditya.adityacicdapp
       inapp-update-priority: '1.0.0'
       user-fraction: '0.0'
        

