#1
# Test and Deploy
name: Android CI

# Action that will be executed
#Currently Doing On Master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#2
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDevRelease

      - name: Release
        run: |
          version_name=${GITHUB_REF##*/}
          echo "Tagging release with tag $version_name"
          git tag $version_name release/$version_name
          git push origin --tags
      - name: Create service_account.json
        run: echo '${{ secrets.GOOGLE_PLAY }}' > service_account.json


      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.jshvarts.flows
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: development
          whatsNewDirectory: distribution/
